/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qlihavwlcawdkbezflsg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsaWhhdndsY2F3ZGtiZXpmbHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MjUyNzksImV4cCI6MjA3NzMwMTI3OX0.QlEU-ZFR-atkl-AlZ3lNfcnH-2TrwF_tHcXpcn8i9TU"